services:
  ozb-deal-filter:
    build: .
    container_name: ozb-deal-filter
    restart: unless-stopped
    volumes:
      # Configuration files
      - ./config:/app/config:ro
      # Prompt templates
      - ./prompts:/app/prompts:ro
      # Logs directory
      - ./logs:/app/logs
      # Git repository for automated commits
      - ./.git:/app/.git
    environment:
      - CONFIG_PATH=/app/config/config.yaml
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    depends_on:
      - ollama
    networks:
      - ozb-network
    healthcheck:
      test: ["CMD", "python", "-c", "import ozb_deal_filter; print('OK')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    networks:
      - ozb-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

networks:
  ozb-network:
    driver: bridge

volumes:
  ollama_data:
    driver: local