rss_feeds:
- https://www.ozbargain.com.au/deals/shokz.com.au/feed
- https://www.ozbargain.com.au/brand/coros/feed
- https://www.ozbargain.com.au/product/insta360-go-3/feed
- https://www.ozbargain.com.au/tag/iphone/feed
- https://www.ozbargain.com.au/product/iphone-16/feed
- https://www.ozbargain.com.au/product/iphone-15/feed
- https://www.ozbargain.com.au/product/iphone-14/feed
- https://www.ozbargain.com.au/product/iphone-16-pro/feed
- https://www.ozbargain.com.au/product/iphone-16-plus/feed
- https://www.ozbargain.com.au/product/iphone-16e/feed
- https://www.ozbargain.com.au/product/iphone-16/feed
- https://www.ozbargain.com.au/tag/table-tennis-bat/feed
- https://www.ozbargain.com.au/tag/table-tennis-accessory/feed
- https://www.ozbargain.com.au/tag/steam-game/feed
- https://www.ozbargain.com.au/brand/music-streaming%2Bapple/feed
